name: Python CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Define o sistema operacional da máquina virtual do GitHub
    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Python ${{ matrix.pyhton-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requeriments.txt

    - name: Rodar Pytest
      run: |
        pytest