name: Python CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Define o sistema operacional da máquina virtual do GitHub

    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Configurar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn pytest --no-cache-dir

    - name: Rodar Pytest
      run: |
        pytest